### ISSUE TITLE
SSL issues where there shouldn't be any

### ISSUE THREAD

**Issue by axfelix** [mloesch/sickle#10]
Hi,

When trying to use Sickle to hit https://rdmtest1.computecanada.ca/oai/request, which has a valid cert according to Chrome, I get this SSL error:

    Traceback (most recent call last):
      File "globus_harvester.py", line 302, in <module>
    oai_harvest_with_thumbnails(repository)
      File "globus_harvester.py", line 264, in oai_harvest_with_thumbnails
        records = sickle.ListRecords(metadataPrefix='oai_dc', ignore_deleted=True)
      File "/usr/local/lib/python3.5/dist-packages/sickle/app.py", line 129, in ListRecords
        return self.iterator(self, params, ignore_deleted=ignore_deleted)
      File "/usr/local/lib/python3.5/dist-packages/sickle/iterator.py", line 135, in __init__
        super(OAIItemIterator, self).__init__(sickle, params, ignore_deleted)
      File "/usr/local/lib/python3.5/dist-packages/sickle/iterator.py", line 46, in __init__
        self._next_response()
      File "/usr/local/lib/python3.5/dist-packages/sickle/iterator.py", line 138, in _next_response
        super(OAIItemIterator, self)._next_response()
      File "/usr/local/lib/python3.5/dist-packages/sickle/iterator.py", line 84, in _next_response
        self.oai_response = self.sickle.harvest(**params)
      File "/usr/local/lib/python3.5/dist-packages/sickle/app.py", line 102, in harvest
        auth=self.auth)
      File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 71, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 57, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 585, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 477, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

This is after installing certifi which normally works around Python SSL issues, and updating requests. Can duplicate in 2.7.11 and 3.5.1.

Is there an easy way of just passing verify=False to sickle, assuming I can't get Python to accept this cert?

**Comment by axfelix** [comment]
Nevermind, this was me.

**Comment by DoomHammer** [comment]
> Nevermind, this was me.

Can you elaborate what the problem was?
