### ISSUE TITLE
Python3 sickle?

### ISSUE THREAD

**Issue by TuulaP** [mloesch/sickle#31]
Hi, should sickle work in python3?  I converted one of my old python scripts to python3 via 2to3 but getting now some errors with sickle. 

When script has just

> from sickle import Sickle

getting with (anaconda) python 3.6.8 error : 

```
Traceback (most recent call last):
  File "minikoe.py", line 3, in <module>
    from sickle import Sickle
  File "c:\softat\anaconda3\lib\site-packages\sickle\__init__.py", line 13, in <module>
    from .app import Sickle
  File "c:\softat\anaconda3\lib\site-packages\sickle\app.py", line 15, in <module>
    from sickle.iterator import BaseOAIIterator, OAIItemIterator
  File "c:\softat\anaconda3\lib\site-packages\sickle\iterator.py", line 12, in <module>
    from sickle.models import ResumptionToken
  File "c:\softat\anaconda3\lib\site-packages\sickle\models.py", line 11, in <module>
    from lxml import etree
ImportError: cannot import name 'etree'  

```

I'll check if my lxml is too old or what ...

**Comment by mloesch** [comment]
Cannot reproduce.
